@startuml

title __WEATHER's Class Diagram__\n

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.Cloud {
          ~ all : int
          + Cloud()
          + getAll()
          + setAll()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.Coordinate {
          ~ lat : float
          ~ lon : float
          + Coordinate()
          + getLat()
          + getLon()
          + setLat()
          + setLon()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.MainW {
          ~ feelsLike : float
          ~ humidity : float
          ~ pressure : float
          ~ temMax : float
          ~ temp : float
          ~ tempMin : float
          + MainW()
          + getFeelsLike()
          + getHumidity()
          + getPressure()
          + getTemMax()
          + getTemp()
          + getTempMin()
          + setFeelsLike()
          + setHumidity()
          + setPressure()
          + setTemMax()
          + setTemp()
          + setTempMin()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.SystemW {
          ~ ID_system : int
          ~ country : String
          ~ sunrise : int
          ~ sunset : int
          ~ type : int
          + SystemW()
          + getCountry()
          + getID_system()
          + getSunrise()
          + getSunset()
          + getType()
          + setCountry()
          + setID_system()
          + setSunrise()
          + setSunset()
          + setType()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.Weather {
          ~ ID_weather : int
          ~ description : String
          ~ icon : String
          ~ main : String
          + Weather()
          + Weather()
          + getDescription()
          + getID_weather()
          + getIcon()
          + getMain()
          + setDescription()
          + setID_weather()
          + setIcon()
          + setMain()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.weather {
      class es.ull.patrones.weather.Wind {
          ~ deg : float
          ~ gust : float
          ~ speed : float
          + Wind()
          + getDeg()
          + getGust()
          + getSpeed()
          + setDeg()
          + setGust()
          + setSpeed()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
